version: '3.9'

services:
  frontend:
    build:
      context: ./coruBusFront
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./coruBusApi
      dockerfile: Dockerfile
    ports:
      - "5234:5234"
    volumes:
      - ./coruBusApi/Database:/app/Database
