version: '3.9'

services:
  frontend:
    build:
      context: ./coruBusFront
      dockerfile: Dockerfile
    ports:
     - "30000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./coruBus.Api
      dockerfile: Dockerfile
    ports:
      - "5234:5234"
    volumes:
      - ./coruBus.Api/Database:/app/Database
