### Definir la dirección base del host
@coruBus_HostAddress = http://localhost:5234

### (Devuelve toda la informacion de las lineas)
GET {{coruBus_HostAddress}}/api/getLineas
Accept: application/json

### (Devuelve info actual de las lineas para la parada seleccionada)
POST  {{coruBus_HostAddress}}/api/getBusesParada
Accept: application/json

523

### (devuelve todas las paradas )
GET {{coruBus_HostAddress}}/api/getParadas
Content-Type: application/json
Accept: application/json

