### Definir la dirección base del host
@coruBus_HostAddress = http://localhost:5234

### (Devuelve toda la informacion de las lineas)
GET {{coruBus_HostAddress}}/api/getLineas
Accept: application/json

### (Devuelve la información de cada linea para la parada seleccionada)
GET {{coruBus_HostAddress}}/api/getBusesParada
Accept: application/json

### (devuelve la información de las paradas de una linea concreta )
POST  {{coruBus_HostAddress}}/api/paradas
Content-Type: application/json
Accept: application/json

42