### Definir la dirección base del host
@coruBus_HostAddress = http://localhost:5234

### (Devuelve toda la informacion de las lineas)
GET {{coruBus_HostAddress}}/api/getLineas
Accept: application/json

### (Devuelve info actual de las lineas para la parada seleccionada)
POST  {{coruBus_HostAddress}}/api/getBusesParada
Accept: application/json

523

### (devuelve todas las paradas )
GET {{coruBus_HostAddress}}/api/getParadas
Content-Type: application/json
Accept: application/json

### (recibe las paradas para analitica)
POST  {{coruBus_HostAddress}}/api/sendParadasData
Content-Type: application/json
Accept: application/json

{
  "Paradas": [
    { "Id": 1, "Count": 3 },
    { "Id": 2, "Count": 1 }
  ]
}

### (devuelve todas las paradas )
GET {{coruBus_HostAddress}}/api/ping
Accept: application/json
